version: "3.8"

services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: superbenchmark_user
      POSTGRES_PASSWORD: superbenchmark_password
      POSTGRES_DB: superbenchmark_db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    depends_on:
      - db
    environment:
      SUPERBENCHMARK_DEBUG: ${SUPERBENCHMARK_DEBUG}
      DATABASE_URL: ${DATABASE_URL}
    volumes:
      - .:/app
    ports:
      - "8000:8000"

volumes:
  db_data:
